Romain
WildCodeSchool/2022-09-JS-Lille-project-3-g3-origin pull request #12
Opened 2022-12-15 16:10 UTC by Fostrankill

2022-12-15 16:23 UTC, cartige approved these changes, later dismissed

2022-12-16 11:37 UTC, LoicBrassart requested changes
Remove useless changes and it's okay!

2022-12-16 11:37 UTC, LoicBrassart commented on frontend/src/pages/Home/Home.jsx
> +
Why add this empty space ?

2022-12-16 11:37 UTC, LoicBrassart commented on frontend/src/pages/Home/Home.jsx
> +      });
Even though ESLint lets you do this, it has no meaning, remove it

2022-12-16 11:55 UTC, Fostrankill reviewed
Add Modification

2022-12-16 11:55 UTC, cartige approved these changes

2022-12-16 13:01 UTC, LoicBrassart approved these changes
No more Evil

2022-12-16 13:02 UTC, merged