add basic routes for users and videos
WildCodeSchool/2022-09-JS-Lille-project-3-g3-origin pull request #16
Opened 2022-12-19 13:37 UTC by cartige

2022-12-19 13:39 UTC, PriscilliaAmmeux submitted a review, later dismissed

2022-12-19 16:12 UTC, LoicBrassart requested changes
Useess lib in backend

2022-12-19 16:12 UTC, LoicBrassart commented on backend/package.json
> +    "axios": "^1.2.1",
Don't axios my backend!

2022-12-20 08:21 UTC, PriscilliaAmmeux approved these changes

2022-12-20 08:44 UTC, LoicBrassart approved these changes
SnE

2022-12-20 16:23 UTC, merged