Profil page
WildCodeSchool/2022-09-JS-Lille-project-3-g3-origin pull request #37
Opened 2023-01-24 10:36 UTC by Atouzani7

Style

2023-01-24 10:46 UTC, cartige submitted a review, later dismissed

2023-01-25 08:14 UTC, cartige commented on .gitignore
>  .DS_Store
.DS_Store, two times

2023-01-25 08:15 UTC, cartige requested changes
Remove one ".DS_Store" from .gitignore

2023-01-25 08:54 UTC, cartige approved these changes

2023-01-25 10:38 UTC, LoicBrassart approved these changes
SnE

2023-01-25 10:50 UTC, merged