Subscription form
WildCodeSchool/2022-09-JS-Lille-project-3-g3-origin pull request #4
Opened 2022-12-08 13:05 UTC by CharlyJuteau

2022-12-08 14:07 UTC, cartige submitted a review, later dismissed

2022-12-09 10:08 UTC, LoicBrassart requested changes
Look this video, and fix your z-indexes please

https://youtu.be/uS8l4YRXbaw

2022-12-09 10:08 UTC, LoicBrassart commented on frontend/src/components/Modal/modal.scss
> +  z-index: 1040;
You don't understand z-index?I suppose ? -_-

2022-12-09 10:08 UTC, LoicBrassart commented on frontend/src/components/Modal/modal.scss
> +  z-index: 1050;
You don't understand z-index?I suppose ? -_-

2022-12-09 10:08 UTC, LoicBrassart commented on frontend/src/components/Modal/modal.scss
> +  z-index: 100;
You don't understand z-index?I suppose ? -_-

2022-12-14 08:19 UTC, cartige approved these changes

2022-12-14 09:07 UTC, LoicBrassart approved these changes
Better

2022-12-14 09:11 UTC, merged