Api call part2
WildCodeSchool/2022-09-JS-Lille-project-3-g3-origin pull request #55
Opened 2023-01-28 22:42 UTC by cartige

Relocate api calls, and like button handled

2023-01-30 09:19 UTC, PriscilliaAmmeux approved these changes, later dismissed

2023-01-30 11:52 UTC, LoicBrassart requested changes
One minor Evil

2023-01-30 11:52 UTC, LoicBrassart commented on frontend/src/components/SearchBarDetails/SearchBarDetails.jsx
> +  const [selectedRadio, setSelectedRadio] = useState();
Missing initial value

2023-01-30 16:08 UTC, PriscilliaAmmeux approved these changes

2023-01-31 07:50 UTC, LoicBrassart approved these changes
SnE

2023-01-31 08:06 UTC, merged